### ISSUE TITLE
Unnecessary; cleanup!

### ISSUE THREAD

**Issue by carlodandan** [abkdmn-ng/twrp_motorola_rhodei#2]
Instead of renaming files, why not just remove it? What's the point of not doing that? Those are unnecessary.

This one:
https://github.com/abkdmn-ng/twrp_motorola_rhodei/blob/8c9d05132f8e5a901ea97adfbef5cac5e9ddfff6/a

And even this one:
https://github.com/abkdmn-ng/twrp_motorola_rhodei/blob/8c9d05132f8e5a901ea97adfbef5cac5e9ddfff6/w#L1

It may not cause any trouble in your build but still not needed.

**Comment by abkdmn-ng** [comment]
I was deleting it but it wasn't getting deleted.

**Comment by abkdmn-ng** [comment]
> Instead of renaming files, why not just remove it? What's the point of not doing that? Those are unnecessary.
> 
> This one: https://github.com/abkdmn-ng/twrp_motorola_rhodei/blob/8c9d05132f8e5a901ea97adfbef5cac5e9ddfff6/a
> 
> And even this one:
> 
> https://github.com/abkdmn-ng/twrp_motorola_rhodei/blob/8c9d05132f8e5a901ea97adfbef5cac5e9ddfff6/w#L1
> 
> It may not cause any trouble in your build but still not needed.

I removed it
